from langchain.agents import create_agent
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from tools import web_search, scrape_url
from dotenv import load_dotenv

load_dotenv()

llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash", temperature=0.2, max_output_tokens=1024)

def build_search_agent():
    """Builds a search agent using langchainthat can perform web searches using the web_search tool."""
    return create_agent(
        model=llm,
        tools=[web_search])

def build_reader_agent():
    """Builds a reader agent using langchain that can scrape and read content from URLs using the scrape_url tool"""
    return create_agent(
        model=llm,
        tools=[scrape_url])

#writer chain
"""Builds a writer chain using modern LCEL pipeline to generate a detailed research report based on the output of the search and reader agents."""

writer_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are an expert research writer. Write clear, structured and insightful reports."),
    ("human", """Write a detailed research report on the topic below.

Topic: {topic}

Research Gathered:
{research}

Structure the report as:
- Introduction
- Key Findings (minimum 3 well-explained points)
- Conclusion
- Sources (list all URLs found in the research)

Be detailed, factual and professional."""),
])

writer_chain = writer_prompt | llm | StrOutputParser()

#critic_chain
"""Builds a critic chain using modern LCEL pipeline to critique and score the research report generated by the writer chain."""
critic_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a sharp and constructive research critic. Be honest and specific."),
    ("human", """Review the research report below and evaluate it strictly.

Report:
{report}

Respond in this exact format:

Score: X/10

Strengths:
- ...
- ...

Areas to Improve:
- ...
- ...

One line verdict:
..."""),
])

critic_chain = critic_prompt | llm | StrOutputParser()
